### ISSUE TITLE
New Website Design/Theme

### ISSUE THREAD

**Issue by Swordington** [Strand-Custom-Commands/Strand-Website#2]
Check #brainstorm on the Discord Server for more info on the themes. **Major project, probably better on a dev branch for simplicity.**

**Comment by Swordington** [comment]
Are we still going to go ahead with this?

**Comment by ghost** [comment]
> Are we still going to go ahead with this?

I don't think so. We could continue, but our current website is fine.

**Comment by Swordington** [comment]
Ok - Closing out issue and we can leave dev branch for now.
