### ISSUE TITLE
.tk links not redirecting

### ISSUE THREAD

**Issue by ghost** [Strand-Custom-Commands/Strand-Website#3]
The following links appear not to redirect:
- https://strandcc.tk/
- https://www.strandcc.tk/

The following links redirect:
- www.strandcc.tk
- http://strandcc.tk
- http://www.strandcc.tk

**Comment by Swordington** [comment]
Working on a fix now.

**Comment by Swordington** [comment]
Fix pushed - should work now

**Comment by Swordington** [comment]
Works
